### PR TITLE
Added Django and REACT framework

### PR DESCRIPTION
**Pull request by ArushiSinghal**
Added Django and REACT frontend app, so that contributors can add features to it.

### CODE REVIEW

**Comment by ArushiSinghal** [comment]
@alok760 @Soumya0803 Please review

**Comment by alok760** [comment]
@ArushiSinghal I appreciate the effort and this looks like a nice first step.
Although I suggest you - look for other Pull Requests in the project before making a new one :D.
See #1 where these steps needed to be discussed further
Also at this point in time, we are focussing more on project design and workflow rather than implementation. see https://github.com/ContriFOSS/project_template

but I'm merging #1 and since you've already started I suggest to do the following changes in this PR 
* retain the documentation for Django.
* I'll create another repository for frontend where you can push everything related to ReactJS.

**Comment by alok760** [comment]
@ArushiSinghal I have made a new repository for Frontend - https://github.com/ContriFOSS/ContriFOSS-Frontend
Add your ReactJS related contribution there.

**Comment by ArushiSinghal** [comment]
@alok760 I have created new PR

**Comment by Soumya0803** [comment]
Hi @ArushiSinghal. Closing this as you have created a new PR in https://github.com/ContriFOSS/ContriFOSS-Frontend

**Pull request closed without merging**
